name: storybook deploy

on:
  push:
    branches: master
    paths:
      - "**.stories.ts"
      - "**.stories.tsx"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Repository checkout
        uses: actions/checkout@v3

      # 2. node js 설정
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. 의존성 설치 및 캐싱
      - name: Package dependencies
        run: pnpm install

      # 4. Storybook 빌드
      - name: Build Storybook
        run: pnpm build:storybook

      # 5. 결과물을 gh-pages 브랜치로 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/docs/storybook-static
